services:
  db-schedule:
    networks:
      - schedule-network
    image: postgres:12-alpine
    container_name: schedule-db-container
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - schedule-db:/var/lib/postgres/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql


  app-schedule:
    networks:
      - schedule-network
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule-app-container
    depends_on:
      - db-schedule
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_PROFILES_ACTIVE
networks:
  schedule-network:
    driver: bridge

volumes:
  schedule-db: # Define a named volume for MySQL data persistence