spring:
  datasource:
    url: jdbc:h2:mem:communicationdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-plarform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  # /api-docs endpoint custom path
  api-docs:
    path: /api-docs
